
% run_tracker.m

close all;
% clear all;

%choose the path to the videos (you'll be able to choose one with the GUI)
base_path = 'F:/Project/OTB100/sequences/';% 'sequences/';%'C:/Users/iva/Desktop/其他/Temple-color-128/Temple-color-128/'%C:\Users\iva\Desktop\其他\vot2016

OTB2013Set = {'Basketball', 'Doll', 'Bolt', 'Soccer', 'Deer', 'Boy', 'CarDark', 'CarScale',...
          'David', 'David3', 'Football1', 'Girl', 'Crossing',...
          'MountainBike', 'Shaking', 'Singer1', 'Singer2', 'Skating1',...
          'Trellis', 'Walking', 'Walking2', 'Woman', 'Tiger1', 'MotorRolling',...
          'Lemming', 'Matrix', 'Coke', 'FaceOcc1', 'Liquor', 'Skiing', 'Tiger2', 'Ironman', 'Couple',...
          'Car4', 'Subway', 'David2', 'Dog1', 'Dudek', 'FaceOcc2', 'Fish', 'FleetFace',...
          'Football', 'Freeman1', 'Freeman3', 'Freeman4', 'Jogging-1', 'Jogging-2',...
          'Jumping', 'Mhyang', 'Suv', 'Sylvester'};
OTB100Set = {'Basketball', 'Doll', 'Bolt', 'Soccer', 'Deer', 'Boy', 'CarDark', 'CarScale',...
          'David', 'David3', 'Football1', 'Girl', 'Crossing',...
          'MountainBike', 'Shaking', 'Singer1', 'Singer2', 'Skating1',...
          'Trellis', 'Walking', 'Walking2', 'Woman', 'Tiger1', 'MotorRolling',...
          'Lemming', 'Matrix', 'Coke', 'FaceOcc1', 'Liquor', 'Skiing', 'Tiger2', 'Ironman', 'Couple',...
          'Car4', 'Subway', 'David2', 'Dog1', 'Dudek', 'FaceOcc2', 'Fish', 'FleetFace',...
          'Football', 'Freeman1', 'Freeman3', 'Freeman4', 'Jogging-1', 'Jogging-2',...
          'Jumping', 'Mhyang', 'Suv', 'Sylvester','Biker','Bird1','Bird2','BlurBody','BlurCar1','BlurCar2','BlurCar3','BlurCar4',...
          'BlurFace','BlurOwl','Board','Bolt2','Box','Car1','Car2','Car24','ClifBar','Coupon','Crowds','Dancer','Dancer2',...
          'Diving','Dog','DragonBaby','Girl2','Gym','Human2','Human3','Human4-2','Human5','Human6','Human7','Human8','Human9',...
          'Jump','KiteSurf', 'Man','Panda','RedTeam','Rubik','Skater','Skater2','Skating2-1','Skating2-2','Surfer','Toy','Trans','Twinnings','Vase'};
      OTB100rmSet = {'Basketball', 'Doll', 'Bolt', 'Soccer', 'Deer', 'CarDark', 'CarScale',...
          'David', 'David3', 'Football1', 'Girl', 'Crossing',...
          'MountainBike', 'Shaking', 'Singer1', 'Singer2', 'Skating1',...
          'Trellis', 'Walking', 'Walking2', 'Woman', 'Tiger1', 'MotorRolling',...
            'Coke', 'FaceOcc1', 'Liquor', 'Skiing',...
          'Car4', 'Subway', 'David2', 'Dog1', 'Dudek', 'FaceOcc2', 'Fish', 'FleetFace',...
           'Freeman1', 'Freeman3', 'Freeman4', 'Jogging-1', 'Jogging-2',...
          'Mhyang', 'Suv', 'Sylvester','BlurBody','BlurCar2','BlurCar4',...
          'Bolt2','Box','Car1','Car2','Car24','ClifBar','Coupon','Crowds','Dancer','Dancer2',...
          'Diving','Dog','Gym','Human2','Human4-2','Human5','Human8',...
          'Jump','Man','Panda','RedTeam','Rubik','Skater','Skater2','Toy','Trans','Vase'};
OTB50nsrmSet = {'Basketball', 'Bolt', 'Soccer', 'Deer','David', ...
          'Shaking', 'Singer2', 'Skating1',...
          'Trellis', 'Walking', 'Walking2', 'Woman', 'MotorRolling',...
           'Liquor',...
          'Car4','Dudek',...
          'Sylvester','BlurBody','BlurCar2',...
          'Box','Car1','ClifBar',...
          'Diving','Human4-2',...
          'Jump'};%Football,Lemming,Girl2,Human3,Human6

Failure = {'MotorRolling','Matrix','Skiing','Ironman','Couple','Fish','Biker','Bird2','Lemming','BlurOwl','Board','Bolt2','Box','Diving', 'Jump',...
            'Skating2-1','Skating2-2','Girl2','Human2','Human3','Human5'};
Failure1 = {'Woman','MotorRolling','Lemming','Matrix','Skiing','Ironman','Football','Freeman1','Freeman3','Jumping','Sylvester','Biker',...
            'Bird1','BlurBody','BlurOwl','Board','Bolt2','Box','Diving','DragonBaby','Girl2','Human2','Human3','Human4-2','Human5','Human6',...
            'Human7','Jump','KiteSurf','Panda','Skater2','Skating2-1','Skating2-2'};
Deformation = {'Basketball','Bird1','Bird2','BlurBody','Bolt','Bolt2', 'Couple', 'Crossing','Crowds','Dancer','Dancer2','David','David3','Diving','Dog',...
            'Dudek','FleetFace','Girl2','Gym','Human3','Human4-2','Human5','Human6','Human7','Human8','Human9','Jogging-1', 'Jogging-2','Jump',...
            'Mhyang','Panda','Singer2','Skater','Skater2','Skating1','Skating2-1','Skating2-2','Skiing','Subway','Tiger1','Tiger2','Trans',...
            'Walking', 'Woman'};
Fast_Motion = {'Bird1','Bird2','BlurBody', 'BlurFace','BlurOwl','Board','BlurCar1','BlurCar2','BlurCar3','BlurCar4','Boy','CarScale','ClifBar','Coke',...
            'Couple','Deer','DragonBaby','Dudek','FleetFace','Human6','Human7','Human9','Ironman','Jumping','Lemming','Liquor','Matrix','MotorRolling',...
            'Skater2','Skating2-1','Skating2-2','Soccer','Surfer','Tiger1','Tiger2','Toy', 'Woman','Vase'};
Occlusion = {'Basketball','Biker','Bird2','Bolt','Box','CarScale','ClifBar','Coke','Coupon','David','David3','Doll','DragonBaby','Dudek','FaceOcc1','FaceOcc2',...
            'Football','Freeman4', 'Girl', 'Girl2','Human3','Human4-2','Human5','Human6','Human7','Ironman','Jogging-1', 'Jogging-2','Jump','KiteSurf',...
             'Lemming', 'Liquor','Matrix','Panda','RedTeam','Rubik','Singer1','Skating1','Skating2-1','Skating2-2','Soccer','Subway', 'Suv','Tiger1','Tiger2',...
              'Walking', 'Walking2', 'Woman','Trans'};
          
OTB50Set = {'Basketball', 'Bolt', 'Soccer', 'Deer', 'CarDark', 'CarScale',...
          'David', 'Girl',...
          'Shaking', 'Singer2', 'Skating1',...
          'Trellis', 'Walking', 'Walking2', 'Woman', 'MotorRolling',...
          'Matrix', 'Liquor', 'Skiing', 'Tiger2', 'Ironman', 'Couple',...
          'Car4','Dudek',...
          'Football', 'Freeman4',...
          'Jumping', 'Sylvester','Biker','Bird1','BlurBody','BlurCar2',...
          'BlurFace','BlurOwl','Box','Car1','ClifBar','Crowds',...
          'Diving','DragonBaby','Human3','Human4-2','Human6','Human9',...
          'Jump','Panda','RedTeam','Skating2-1','Skating2-2','Surfer'};
VOT2016Set = {'bag','ball1','ball2','basketball','birds1','birds2','blanket','bmx','bolt1','bolt2','book','butterfly','car1','car2','crossing','dinosaur',...
            'fernando','fish1','fish2','fish3','fish4','girl','glove','godfather','graduate','gymnastics1','gymnastics2','gymnastics3','gymnastics4',...
            'hand','handball1','handball2','helicopter','iceskater1','iceskater2','leaves','marching','matrix','motocross1','motocross2','nature',...
            'octopus','pedestrian1','pedestrian2','rabbit','racing','road','shaking','sheep','singer1','singer2','singer3','soccer1','soccer2','soldier',...
            'sphere','tiger','traffic','tunnel','wiper'};
colorSet = {'Basketball', 'Soccer', 'Bolt', 'Doll', 'Boy', 'CarDark', 'CarScale', 'Crossing',...
            'David', 'David3', 'Deer', 'Football1', 'Girl',...
            'MountainBike', 'Shaking', 'Singer1', 'Singer2', 'Skating1', 'MotorRolling'...
            'Subway', 'Trellis', 'Walking', 'Walking2', 'Woman', 'Tiger1', 'Jogging-1', 'Jogging-2'...
            'Lemming', 'Matrix', 'Coke', 'FaceOcc1', 'Liquor', 'Skiing', 'Tiger2', 'Ironman', 'Couple'};
TC128Set = { 'Airport_ce','Baby_ce','Badminton_ce1','Badminton_ce2','Ball_ce1','Ball_ce2','Ball_ce3','Ball_ce4','Basketball','Basketball_ce1',...
            'Basketball_ce2','Basketball_ce3','Bee_ce','Bicycle','Biker','Bikeshow_ce','Bike_ce1','Bike_ce2','Bird','Board','Boat_ce1','Boat_ce2','Bolt',...
            'Boy','Busstation_ce1','Busstation_ce2','Carchasing_ce1','Carchasing_ce3','Carchasing_ce4','CarDark','CarScale','Charger_ce','Coke','Couple','Crossing','Cup',...
            'Cup_ce','David','David3','Deer','Diving','Doll','Eagle_ce','Electricalbike_ce','FaceOcc1','Face_ce','Face_ce2','Fish_ce1','Fish_ce2','Football1',...
            'Girl','Girlmov','Guitar_ce1','Guitar_ce2','Gym','Hand','Hand_ce1','Hand_ce2','Hurdle_ce1','Hurdle_ce2','Iceskater','Ironman','Jogging1','Jogging2','Juice',...
            'Kite_ce1','Kite_ce2','Kite_ce3','Kobe_ce','Lemming','Liquor','Logo_ce','Matrix','Messi_ce','Michaeljackson_ce','Microphone_ce1','Microphone_ce2',...
            'Motorbike_ce','MotorRolling','MountainBike','Panda','Plane_ce2','Plate_ce1','Plate_ce2','Pool_ce1','Pool_ce2','Pool_ce3','Railwaystation_ce',...
            'Ring_ce','Sailor_ce','Shaking','Singer1','Singer2','Singer_ce1','Singer_ce2','Skating1','Skating2','Skating_ce1','Skating_ce2','Skiing','Skiing_ce',...
            'Skyjumping_ce','Soccer','Spiderman_ce','Subway','Suitcase_ce','Sunshade','SuperMario_ce','Surf_ce1','Surf_ce2','Surf_ce3','Surf_ce4','TableTennis_ce',...
            'TennisBall_ce','Tennis_ce1','Tennis_ce2','Tennis_ce3','Thunder_ce','Tiger1','Tiger2','Torus','Toyplane_ce','Trellis','Walking','Walking2','Woman',...
            'Yo-yos_ce1','Yo-yos_ce2','Yo-yos_ce3'};       
graySet = {'Car4', 'David2', 'Dog1', 'Dudek', 'FaceOcc2', 'Fish', 'FleetFace',...
           'Football', 'Freeman1', 'Freeman3', 'Freeman4', ...
           'Jumping', 'Mhyang', 'Suv', 'Sylvester'};
hard = {'Basketball','Bolt','Singer2','Shaking','CarScale','Liquor','Couple','Jogging-1','Soccer' ,...
        'Deer','Tiger1' };
    small_size = {'Biker','Bird1','Car24','CarDark','CarScale','Crossing','Crowds','David2','Football1'...
          ,'Freeman1','Freeman3','Freeman4','Girl','Human5','Human6','Jumping','KiteSurf','Man','Panda','RedTeam','Skiing','Subway','Surfer'};
 small_size_rm = {'Car24','CarDark','CarScale','Crossing','Crowds','David2','Football1'...
          ,'Freeman1','Freeman3','Freeman4','Girl','Human5','Man','Panda','RedTeam','Skiing','Subway',};
out_of_plane_rotation = {};
singleSet = {'Basketball'};
testSet = OTB2013Set;  %OTB100rmSet
user_choose = 1;
params.debug = 0;

params.gap = 6;

params.learning_rate_cn_color = 0.0174;% 0.0174
params.learning_rate_cn_gray = 0.0175;%0.0175
params.learning_rate_hog_color = 0.0173;%0.0173 0.0175(OTB00)
params.learning_rate_hog_gray = 0.018;%0.018
params.num_compressed_dim_cn = 4;
params.num_compressed_dim_hog = 4;
%parameters according to the paper
params.padding = 1.5;         			   % extra area surrounding the target
params.output_sigma_factor = 1/16;%1/16		   % spatial bandwidth (proportional to target)
params.scale_sigma_factor = 1/16;          % standard deviation for the desired scale filter output
params.lambda = 1e-2;					   %  Scale regularization (denoted "lambda" in the paper)
params.interp_factor = 0.025;			% tracking model learning rate (denoted "eta" in the paper)
params.cn_features = {'cn10'}; % features that atranslation_vec = [trans_row, trans_col] .* (img_support_sz./output_sz) * currentScaleFactor * scaleFactors(scale_ind);re not compressed, a cell with strings (possible choices: 'gray', 'cn')
params.hog_features = {'hog'}; % features that are compressed, a cell with strings (possible choices: 'gray', 'cn')

params.cnSigma_color = 0.515;%0.515
params.hogSigma_color = 0.6;%0.6

params.cnSigma_gray = 0.3;%0.3
params.hogSigma_gray = 0.4;%0.4
params.refinement_iterations = 1;       % number of iterations used to refine the resulting position in a frame
params.translation_model_max_area = inf; % maximum area of the translation model
params.interpolate_response = 1;        % interpolation method for the translation scores
params.lamda=0.01;
params.number_of_scales = 20;    % 20      % number of scale levels
params.number_of_interp_scales = 39; %39   % number of scale levels after interpolation
params.scale_model_factor = 1.0;        % relative size of the scale sample
params.scale_step = 1.02;               % Scale increment factor (denoted "a" in the paper)
params.scale_model_max_area = 512;      % the maximum size of scale examples
params.s_num_compressed_dim = 'MAX';    % number of compressed scale feature dimensions'MAX'

params.visualization = 0;

%ask the user for the video
if user_choose==0
    video_path = choose_video(base_path);
    if isempty(video_path), return, end  %user cancelled
    [img_files, pos, target_sz, ground_truth, video_path] = ...
        load_video_info(video_path);
    params.video_path = video_path;
    params.init_pos = floor(pos) + floor(target_sz/2);
    params.wsize = floor(target_sz);
    params.img_files = img_files;
    [positions, fps] = MKCF_tracker(params);
    % calculate precisions
    [distance_precision, PASCAL_precision, average_center_location_error,Overlap, flag] = ...
        compute_performance_measures(positions, ground_truth);

    fprintf('Center Location Error: %.3g pixels\nDistance Precision: %.3g %%\nOverlap Precision: %.3g %%\nOverlap: %.3g%%\nSpeed: %.3g fps\n', ...
        average_center_location_error, 100*distance_precision, 100*PASCAL_precision,100*Overlap, fps);

else
    average_center_location_error_sum=0;
    distance_precision_sum=0;
    PASCAL_precision_sum=0;
    Overlap_sum=0;
    fps_sum=0;
    for i = 1:length(testSet)
        video_path = [base_path testSet{i} '/'];
        [img_files, pos, target_sz, ground_truth, video_path] = ...
            load_video_info(video_path);
        params.video_path = video_path;
        params.init_pos = floor(pos) + floor(target_sz/2);
        params.wsize = floor(target_sz);
        params.img_files = img_files;
        [positions, fps, tran] = MKCF_tracker(params);
        [distance_precision, PASCAL_precision, average_center_location_error, Overlap, flag] = ...
            compute_performance_measures(positions, ground_truth, 20, 0.5, tran);
        %         if flag
        disp([testSet{i} ': ' num2str(Overlap)]);
        %         end
        average_center_location_error_sum=average_center_location_error_sum+average_center_location_error;
        distance_precision_sum=distance_precision_sum+distance_precision;
        PASCAL_precision_sum=PASCAL_precision_sum+PASCAL_precision;
        Overlap_sum=Overlap_sum+Overlap;
        fps_sum=fps_sum+fps;
        %         im = imread([params.video_path params.img_files{1}]);
        %         if size(im,3)==1
        %             disp([testSet{i}]);
%                 end
    end
    average_center_location_error=average_center_location_error_sum/length(testSet);
    distance_precision=distance_precision_sum/length(testSet);
    PASCAL_precision=PASCAL_precision_sum/length(testSet);
    Overlap=Overlap_sum/length(testSet);
    fps=fps_sum/length(testSet);
    fprintf('Center Location Error: %.3g pixels\nDistance Precision: %.3g %%\nOverlap Precision: %.5g %%\nOverlap: %.5g%%\nSpeed: %.5g fps\n', ...
        average_center_location_error, 100*distance_precision, 100*PASCAL_precision,100*Overlap, fps);
end
